---
title: "Summary of VAVP introductions"
bibliography: references.bib

---

The summaries given here are intended to provide a relatively high level introduction to various topics surrounding Vibro-Acoustic Virtual Prototyping (VAVP) and Transfer Path Analysis, including some more tangentially related subjects. The content is largely reproduced/adapted from the book ['Experimental Vibro-Acoustics'](../book.qmd) [@meggittMoorhouseBook] written by Prof. Andy Moorhouse and I . If you would like more detail on any of the topics discussed, this book would be a good place to start. Some more topic specific references will be given where necessary. 

![Illustration of the VAVP concept. An active vibration source (left component) is coupled to a passive receiver component (right). Source activity due to internal mechanisms (e.g. gear meshing) are represented using concept of equivalent *blocked forces*. The source and receiver components are coupled together by satisfying equilibrium and compatibility between connecting interfaces, a process terms *substructuring*. When combined, these methods enable us to predict the assembly's *operational response*.](VAVP_1.png){width=600 #fig-sigmaPoint}


To help navigate this page and find what you are looking for, here is a brief summary of each introduction:

- *Vibro-Acoustic Virtual Prototyping* - We introduce the concept of virtual prototyping for vibro-acoustic design and describe at a high level the adopted framework.
- *Components* - The VAVP framework is built on the notion of component-level characterisation. In this introduction we discuss some of the particulars of component characterisation, with a focus on passive properties. 
- *Interfaces* - Within the VAVP framework, components are characterised predominantly by their interface dynamics. To substructure an assembly together it is essential that the component's interfaces are appropriately represented. We will discuss various interface representations that can be used within the VAVP framework.
- *Vibration isolators* - Very rarely are vibration sources attached directly to their assemblies. More often, resilient elements, or vibration isolators, are used as an intermediate component to help mitigate the transmission of vibration. We discuss their characterisation for use within the VAVP framework. 
- *Substructuring* - Once all the components in the assembly have been characterised, it is necessary to assemble them to form a model of the coupled system. This assembly process is termed substructuring. 
- *Blocked force* - Central to the VAVP framework is the ability to `turn on' a model to predict an operational response. This requires a description of the active behaviour of any connected vibration sources. This is achieved using the concept of blocked forces. 
- *Uncertainties* - It is fair to argue that the output of a model is meaningless without some estimate of its uncertainty. The same goes for a VAVP. We discuss some methods for quantifying and propagating uncertainty within the VAVP framework.

For more recent developments related to VAVPs and TPA (at least ones that I am involved with) see my [recent papers](../papers/papers.qmd). 

